kaihowl/dotfiles

.github/workflows/test.yml
autojump/install.sh
fzf/install.sh
git/install.sh
nvim/install.sh
nvim/test.sh
pyls/install.sh
ripgrep/install.sh
ripgrep/test.sh
script/bootstrap
script/install
script/test
system/install.sh
tmux/install.sh
virtualenvwrapper/install.sh
virtualenvwrapper/workon.zsh
zsh/install.sh

* automatically set login shell to zsh
* execute all nvim plugin updates headless for CI support
* removed invalid head option from brew reinstall command
* install xclip for stable clipboard support on Ubuntu
* always fail on error during installation

feat: ubuntu 20.04 support, testing with github actions

---

.github/workflows/test.yml
alacritty/install.sh
autojump/install.sh
bin/dots
ccache/install.sh
clangd/install.sh
cmake/install.sh
common/brew.sh
ctags/install.sh
fzf/install.sh
git/install.sh
homebrew/install.sh
mosh/install.sh
ninja/install.sh
ripgrep/install.sh
script/bootstrap
script/install
system/install.sh
tmux/install.sh
zsh/install.sh

Instead of a gigantic `brew upgrade` updating everything on the runner,
we only update what the dotfiles actually control.

feat: faster homebrew bootstrap (on GitHub Actions)

---

.github/workflows/test.yml
nvim/install.sh
nvim/tagbar.test.vim
nvim/test.sh

fix: nvim post-install plugin install

---

nvim/install.sh

fix: add-apt-repository without confirmation.

---

zsh/install.sh

fix: remove deprecated upgrade_oh_my_zsh

---

common/pip.sh
nvim/install.sh
pyls/install.sh

fix: ensure pip3 is installed

---

common/pip.sh

fix: do not print pip3 help output when checking if pip is available

---

virtualenvwrapper/install.sh
virtualenvwrapper/test.sh
virtualenvwrapper/workon.zsh

Virtualenv test

---

nvim/config--nvim--init.vim.symlink
pyls/install.sh

fix: update pylsp to the maintained fork

---

.github/workflows/test.yml

ci: add 20 minute timeout

---

.github/workflows/test.yml
common/brew.sh
homebrew/install.sh
script/install

fix: reduce number of times brew calls cleanup

---

nvim/install.sh

feat: install nvim from binary instead of snap

---

just/install.sh
ripgrep/install.sh

fix: deprecate sha1sum, use sha256

---

nvim/config--nvim--init.vim.symlink
nvim/restorecurpos.test.vim
nvim/test.sh

fix: remove erroneous pipe in :command definition

---

nvim/completion.test.vim
nvim/lsp-clangd.test.vim

Also clarify description of two very similar tests.
Part of #107

test: add logging to flaky test

---

nvim/config--nvim--init.vim.symlink
nvim/nvim-cmp-select-enter.test.vim
nvim/test.sh

fix: only confirm completion item if explicitly selected

---

nvim/config--nvim--init.vim.symlink
nvim/ripgrep.test.vim
nvim/test-ripgrep/testfile.txt

feat: allow passing arguments to Rg with bang version

---

nvim/config--nvim--init.vim.symlink
nvim/ripgrep.test.vim
nvim/test-ripgrep/testfile.txt

fix: ripgrep with hashpound symbol

---

.github/workflows/test.yml
fzf/aliases.zsh
git/aliases.zsh
script/check_for_upgrade.sh
virtualenvwrapper/workon.zsh
zsh/aliases.zsh
zsh/fpath.zsh
zsh/output-complete.zsh
zsh/window.zsh

Switch shellcheck (#137)

---

nvim/config--nvim--init.vim.symlink
nvim/lsp-efm.test.vim
nvim/test-efm/testscript.sh

feat: add basic-nvim config

---

nvim/config--nvim--init.vim.symlink

feat(nvim): add diff to default branch mapping

---

nvim/config--nvim--init.vim.symlink

fix: efm autostart on fugitive buffers

---

nvim/test.sh

test: ensure that all nvim tests are executed

---

zsh/zshrc.symlink

perf(zsh): add easy to enable, permanent profiling code

---

tmux/tmux.conf.symlink

Deconflict ctrl-b for scrolling.
Fixes #175

feat!(tmux): Use ctrl-space as prefix

---

zoxide/install.sh

This does not yet include the manpage fixes.

chore: update zoxide to 8.0.0

---

efm/config--efm-langserver--config.yaml.symlink
nvim/config--nvim--init.vim.symlink
vint/install.sh
vint/test.sh

feat(nvim): add vim-script linter, vim-vint

---

fzf/aliases.zsh

feat: remove duplicates from ctrl-xo tmux completion

---

fzf/install.sh
fzf/test.sh

fix: update fzf on install

---

nvim/config--nvim--init.vim.symlink

fix: nolist for git filetype

---

.github/workflows/test.yml
script/ci.sh
script/test

ci: highlight deprecation warnings

---

nvim/config--nvim--init.vim.symlink

fix(nvim): interactive commands to use Start! and not Make!/Dispatch!

---

nvim/config--nvim--init.vim.symlink
nvim/install.sh

fix(nvim): Do not attempt to load plugins that are not yet installed

---

zsh/userinput.test.expect

test: change phrasing to not annotate expected output as error

---

nvim/config--nvim--init.vim.symlink

feat: add basic conventional commit helpers

---

bin/git-zlog

feat: add basic changelog parser

---

nvim/config--nvim--init.vim.symlink

feat(nvim): replace ctrl-p with simple fzf wrapper

---

nvim/config--nvim--init.vim.symlink

refactor(nvim): organize vimrc in folds

---

alacritty/config--alacritty--alacritty.yml.symlink
nvim/config--nvim--init.vim.symlink
tmux/tmux.conf.symlink

feat: smart pane switching tmux/vim

---

nvim/config--nvim--init.vim.symlink

After the maintainer merged the pending PR for #268, return back to
upstream.

fix(nvim): return back to upstream for asyncrun

---

zsh/install.sh

fix(zsh): allow for unattended upgrade

---

bin/crom

feat(crom): conan create support

---

tmux/statusline.conf

fix(tmux): remove incompatible tmux option

---

zsh/install.sh

Change necessary due to
https://github.blog/2021-09-01-improving-git-protocol-security-github/

fix(zsh): clone omz with https

---

zsh/README.md

chore(zsh): explain zsh profiling

---

.github/workflows/test.yml
bin/git-perf
bin/git-perf-requirements.txt
script/perf.sh

ci: track performance with git-perf 0.2.0

---

.github/workflows/test.yml
git/install.sh

fix: force overwrite git on install with homebrew

---

nvim/config--nvim--init.vim.symlink

use <leader>p for pastetoggle
use <leader>P for markdown preview
Fixes #336

fix: deconflict pastetoggle and markdown preview

---

system/install.sh
system/test.sh

feat: install tree

---

.github/workflows/test.yml
script/versions.sh

feat: report all installed versions

---

nvim/asyncrun-errorformat.test.vim
nvim/config--nvim--init.vim.symlink
nvim/ripgrep.test.vim
nvim/test.sh

fix(nvim): show all output in asyncrun

---

nvim/config--nvim--init.vim.symlink

fix(nvim): include hidden files in live_grep

---

nvim/completion.test.vim
nvim/test.sh

Since #377 was not reproducible locally, add more logging for the next
CI failure.

test(nvim): add more logging

---

script/versions.sh

feat: record pip versions

---

bin/crom

feat(crom): symlink compile_commands.json

---

nvim/config--nvim--init.vim.symlink

feat(nvim): add kotlin syntax

---

script/upgrade.sh

fix(script): macOS only offers /usr/bin/true

---

common/perf.sh
common/perf_stubs.sh
script/install

In local runs replace it with a no-op interface.
Fixes #397

fix(script): only use add_measurement in CI

---

alacritty/install.sh

The snap is outdated. Use a ppa with automated builds instead.
Fixes #326

fix(alacritty): install from PPA

---

colors/change-color

Alacritty is updated to the latest version. That version of alacritty
will also monitor included files (and not just the main file) for
changes.

chore(color): remove force-reload for color changes

---

nvim/test.sh

fix: disable failing test

---

alacritty/install.sh
clangd/install.sh
clangd/test.sh
cmake/install.sh
cmake/test.sh
common/apt.sh

refactor: move apt-add-repository replacement into common function

---

nvim/tests/lsp-efm.test.vim
nvim/tests/test-efm/testscript.vim

test(nvim): vint test

---

.github/workflows/test.yml
nvim/test.sh

test(nvim): parse checkhealth in CI

---

zsh/oh-my.zsh.preamble

fix(zsh): only the script/install drives oh-my-zsh updates

---

nvim/config--nvim--init.vim.symlink
rust/install.sh
rust/test.sh

rust: install stable rust

---

script/versions.sh

fix(script): version report on ubuntu

---

nvim/config--nvim--init.vim.symlink

feat(nvim): clippy linting

---

nvim/config--nvim--init.vim.symlink

Work around issue nerdtree#1321.

fix(nvim): work around nerdtree missing resizing

---

nvim/config--nvim--init.vim.symlink

feat(nvim): open quickfix for running task to right and keep focus

---

cmake/test.sh

test(cmake): test for upstream jammy package for cmake

---

nvim/config--nvim--init.vim.symlink

fix(nvim): switch back to fixed upstream vim-trailing-whitespace

---

zoxide/install.sh

chore(zoxide): update to zoxide 0.9.0

---

zsh/oh-my.zsh.preamble

feat(zsh): switch theme to include git remote status

---

clangd/install.sh
common/download.sh
efm/install.sh
nvim/install.sh
ripgrep/install.sh
rust/install.sh
shellcheck/install.sh
zoxide/install.sh

feat: store installed binaries in local cache

---

nvim/tests/editorconfig.test.vim

test(nvim): disable failing test

---

alacritty/test.sh
ccache/test.sh
clangd/test.sh
colors/test.sh
ctags/test.sh
efm/test.sh
fzf/test.sh
git/test.sh
ninja/test.sh
nvim/test.sh
ripgrep/test.sh
shellcheck/test.sh
system/test.sh
virtualenvwrapper/test.sh
zoxide/test.sh

Just checking their presence on the PATH with `which` does not suffice.

test: check if commands are runnable

---

git/install.sh

fix(git): replace add-apt-repository with safer apt_add_repo

---

.devcontainer/devcontainer.json

ci: add devcontainer

---

nvim/config--nvim--init.vim.symlink

- Missing support for non cwd exploration in carbon
- Missing support for "edit <dir>"

fix(nvim): use nerdtree

---

nvim/config--nvim--init.vim.symlink
nvim/test.sh
nvim/tests/sanitizer-errorformat.test.vim
nvim/tests/test-sanitizer-errorformat/example.cpp

feat(nvim): parse thread sanitizer output

---

gdb/install.sh
gdb/test.sh

fix(gdb): install at least version 10.2 for gdb on Ubuntu

---

clangd/install.sh
clangd/test.sh
cmake/test.sh
efm/install.sh
fzf/install.sh
fzf/test.sh
gdb/install.sh
gdb/test.sh
git/test.sh
homebrew/install.sh
nvim/install.sh
nvim/test.sh
osx/set-defaults.sh
rust/install.sh
rust/test.sh
script/ci.sh
script/install
script/versions.sh
shellcheck/install.sh
system/test.sh
virtualenvwrapper/test.sh
zoxide/install.sh
zoxide/test.sh
zsh/install.sh
zsh/test.sh

chore: reduce logging in CI

---

nvim/config--nvim--init.vim.symlink

feat(nvim): move lsp functionality to fzf-lua

---

script/install
script/test

fix(script): print color escapes correctly

---

rust/install.sh

fix(rust): update rust up hash

---

alacritty/install.sh
common/brew.sh

fix(brew): explicitly upgrade casks

---

common/apt.sh

fix(common): wait for dpkg frontend lock

---

nvim/config--nvim--init.vim.symlink

We don't want unrelated changes from a master/main that further advanced after forking off to muddy the diff output.
Output to master/main for a single file should be equivalent to the pull request preview feature.

feat(nvim): diff to merge-base with main branch

---

nvim/tests/fzf-git.test.vim

test(nvim): catch exceptions in test and report them

---

script/ci.sh

chore: prefix performance measurements for better readability

---

nvim/config--nvim--init.vim.symlink
nvim/tests/fzf-git.test.vim

fix(nvim): unexpected summary line

---

zsh/zshrc.symlink

feat(zsh): automatically start in tmux

---

nvim/nvim-alias.zsh

fix(nvim): workaround for broken terminal with scrollbind

---

common/python.sh
nvim/test.sh

Workaround for #703, reenabling disabled test.

fix(python): force python 3.11 (on macOS)

---

nvim/config--nvim--init.vim.symlink

fix(nvim): no first-time startup error for oil

---

alacritty/config--alacritty--alacritty.toml.symlink

fix(alacritty): correctly name config files for alacritty

---

.github/workflows/test.yml

This reverts commit 5766f662180b925584f644995225f1ba2d11df34.
The daily test was successful.

ci: run once a week

---

nvim/config--nvim--init.vim.symlink
nvim/tests/fzf-git.test.vim

fix(nvim): fzf git log on commit msg

---

nvim/config--nvim--init.vim.symlink
nvim/tests/fzf-git.test.vim

fix(nvim): fzf git log on .github files

---

ccache/test_project/CMakeLists.txt

fix(ccache): suppress warning in test

---

nvim/tests/fzf-git.test.vim

test(nvim): add fzf test for file with leading dash

---

rust/install.sh

fix(rust): update expected hash

---

nvim/tests/fzf-git.test.vim

Fix fzf git tests and reenable

---

nvim/tests/fzf-git.test.vim

test(nvim): check no-sort option for fzf

---

zsh/start-ssh-and-add-identity

feat(zsh): load ssh password from keychain on macOS

---

common/python.sh
pyls/install.sh
vint/install.sh

refactor(python): make common venv functionality available outside nvim

---

revup/install.sh
revup/path.zsh
revup/test.sh

Topic:add-revup
Relative:refactor-venv

feat(revup): add revup

---

common/utilities.sh
virtualenvwrapper/install.sh

refactor(common): extract sed_replace_in_file function

---

ripgrep/install.sh

chore(ripgrep): upgrade to rg 14.1.1

---

nvim/LICENSE

Part of #772
topic:fzf-lua-license

chore(nvim): update fzf-lua license

---

.github/workflows/test.yml

chore(ci): update to latest macOS

---

common/python.sh

fix(common): typo in variable local declaration

---

common/python.sh

fix(common): typo in variable local declaration (#795)

---

zsh/start-ssh-and-add-identity

fix(zsh): ssh agent and auth forwarding

---

script/install

chore(script): add missing newline

---

script/install

feat(script): handle SELinux (by temp disabling it)

---

gdb/install.sh

refactor(gdb): cleaner gdb install flow

---

common/utilities.sh

chore(common): add doc for sed_replace_in_file

---

script/bootstrap

refactor(script): remove superfluous comment

---

alacritty/LICENSE
ccache/LICENSE
ctags/LICENSE
xcode/LICENSE

Part of #772
topic: more-licenses

chore: add more license files

---

virtualenvwrapper/test.sh

chore(virtualenvwrapper): remove debugging output

---

revup/revupconfig.symlink
revup/test.sh

fix(revup): do not overwrite the PR body by default

---

script/bootstrap

fix(script): reduce permissions on symlinked files

---

bin/ssh-bootstrap

Spin up the dotfiles on a remote machine.
topic:remote-bootstrap

feat(bin): add ssh-bootstrap

---

alacritty/install.sh

fix(alacritty): macOS install cannot contain symlinks

---

git/gitconfig.symlink
git/gitconfig_credentials.example
home.nix
script/bootstrap

feat(git): use git-credential-manager (for revup)

---

home.nix
nvim/config--nvim--init.vim.symlink

feat(nvim): move nvim-lspconfig to nix

---

virtualenvwrapper/workon.zsh

fix(virtualenvwrapper): do no leak virtualenvwrapper python into PATH

---

bin/ssh-bootstrap

feat(bin): add more safe guards to ssh-bootstrap

---

.gitignore
flake.lock
flake.nix
gcm/README.md
gcm/flake.lock
gcm/flake.nix
gcm/gcm-client
gcm/gcm-server
git/gitconfig.symlink
home.nix
ssh/ssh-fwd.zsh
tmux/tmux.conf.symlink
zsh/fix-ssh
zsh/start-gcm-helper
zsh/zshrc.symlink

feat(gcm): handle git-credential-manager when remote

---

zsh/install.sh

topic:zsh-powerlevel10k-duplicate

fix(zsh): remove duplicate powerlevel10k inclusion

---

nvim/config--nvim--init.vim.symlink

feat(nvim): revup amend function

---

script/upgrade.sh

feat(script): prevent auto upgrade when not tracking master branch

---

home.nix
nvim/config--nvim--init.vim.symlink
revup/install.sh
revup/path.zsh
revup/test.sh

refactor(revup): install revup with nix

---

efm/config--efm-langserver--config.yaml.symlink
home.nix
vint/install.sh
vint/test.sh

topic: vint-nix
relative: revup-nix
labels:draft

refactor(vint): install vint with nix

---

script/install

topic: fix-non-existent-installer

fix(script): remove non-existent installers for minimal-profile

---

nix/install.sh
script/install

Also makes nix the only bootstrapping installer.
topic: track-nix-time

refactor(script): track nix installation time

---

nvim/test.sh

refactor(nvim): run all tests and report total failures

---

nix/install.sh
script/install

feat: track closure size

---

script/ci.sh

chore: audit test execution time

---

script/ci.sh

feat: audit nix closure size

---

script/test

refactor: add 60s timeout for each test

---

nvim/config--nvim--init.vim.symlink
script/install

Each install invocation should work the same after being called by the
auto update script.
topic:persist-profile

fix(script): persist dotfiles profile

---

bin/ssh-bootstrap

chore(bin): add missing quotes

---

bin/ssh-bootstrap
script/install
ssh/install.sh
ssh/ssh--config_dotfiles.symlink
ssh/ssh-fwd.zsh

This aims to make the underlying forwarding of the GCM socket
transparent to VSCode, etc.
topic:transparent-ssh

feat(ssh): use ssh multiplexing

---

home.nix
nvim/config--nvim--init.vim.symlink

chore(nvim): migrate rust-tools-nvim to nix

---

home.nix
nvim/config--nvim--init.vim.symlink

chore(nvim): move plenary.nvim to nix

---

home.nix
nvim/config--nvim--init.vim.symlink

chore(nvim): move kotlin-vim to nix

---

.gitperfconfig
home.nix
nvim/config--nvim--init.vim.symlink

chore(nvim): move markdown preview nix

---

zsh/test.sh

chore: disable test that times out

---

home.nix
nvim/config--nvim--init.vim.symlink

chore(nvim): move tpope plugins to nix

---

nvim/config--nvim--init.vim.symlink

chore(nvim): remove obsolete fubitive pattern

---

home.nix
nvim/config--nvim--init.vim.symlink

chore(nvim): move two more plugins to nvim

---

nvim/config--nvim--init.vim.symlink

topic:featnvim-omnicomplete-for-revup-in-gitcommit
labels:draft

feat(nvim): omnicomplete for revup in gitcommit

---

home.nix
nvim/config--nvim--init.vim.symlink

topic:chorenvim-move-another-6-plugins-to-nix

chore(nvim): move another 6 plugins to nix

---

script/ci.sh

topic:chorescript-improve-audit-failure-output

chore(script): improve audit failure output

---

script/ci.sh

topic:chorescript-announce-which-part-is-perf-audited

chore(script): announce which part is perf audited

---

home.nix
nvim/config--nvim--init.vim.symlink

topic: chorenvim-move-custom-version-of-juliana-to-nix
relative: chorenvim-move-last-two-easily-available-plugins-to-nix
labels: draft

chore(nvim): move custom version of juliana to nix

---

home.nix
nvim/config--nvim--init.vim.symlink

topic: chorenvim-move-github-color-scheme-to-nix
relative: chorenvim-move-custom-version-of-juliana-to-nix
labels: draft

chore(nvim): move github color scheme to nix

---

.gitperfconfig
home.nix
nvim/config--nvim--init.vim.symlink

topic:chorenvim-move-carbon-to-nix
relative: chorenvim-move-github-color-scheme-to-nix

chore(nvim): move carbon to nix

---

home.nix
nvim/config--nvim--init.vim.symlink

topic:chorenvim-move-stevearcoilnvim-to-nix
relative:chorenvim-move-carbon-to-nix
labels:draft

chore(nvim): move stevearc/oil.nvim to nix

---

home.nix
nvim/config--nvim--init.vim.symlink

topic: chorenvim-move-linediff-to-nix
relative: chorenvim-move-stevearcoilnvim-to-nix
labels:draft

chore(nvim): move linediff to nix

---

home.nix
nvim/config--nvim--init.vim.symlink

topic:chorenvim-move-vim-indent-sentence-to-nix
relative:chorenvim-move-linediff-to-nix
labels:draft

chore(nvim): move vim-indent-sentence to nix

---

nvim/config--nvim--init.vim.symlink

topic: chorenvim-remove-stray-quote-in-config

chore(nvim): remove stray quote in config

---

tmux/tmux.conf.symlink

topic: fixtmux-use-higher-compatibility-term

fix(tmux): use higher compatibility TERM

---

.gitperfconfig
nvim/config--nvim--init.vim.symlink

topic:featnvim-use-experimental-lua-loader

feat(nvim): use experimental lua loader

---

gcm/gcm-server

topic:featgcm-add-rotating-log

feat(gcm): add rotating log

---

efm/config--efm-langserver--config.yaml.symlink
nvim/test.sh

Fixes #765
topic:fixnvim-fix-up-efm-test-and-config

fix(nvim): fix up efm test and config

---

nvim/test.sh

topic:fixnvim-enable-two-flaky-tests-again

fix(nvim): enable two flaky tests again

---

nvim/test.sh

topic:fixnvim-enable-failing-nvim-fzf-test-case-again

fix(nvim): enable failing nvim fzf test case again

---

script/install

topic:chorescript-accept-the-hack

chore(script): accept the hack

---

home.nix

topic:chorenix-convert-non-actionable-todo-into-note

chore(nix): convert non-actionable todo into note

---

nvim/config--nvim--init.vim.symlink

topic:fixnvim-omnitopicslug-calls-incorrectly-spelled-rhubarbcomplete

fix(nvim): OmniTopicSlug calls incorrectly spelled rhubarb#Complete

---

script/versions.sh

We don't use any virtualenv anymore.
topic:fixscript-remove-reporting-for-python

fix(script): remove reporting for python

---

home.nix

topic:docs-state-reason-for-impurity

docs: state reason for impurity

---

nix/install.sh

topic:featnix-automatically-collect-garbage-as-part-of-install

feat(nix): automatically collect garbage as part of install

---

.gitperfconfig
flake.lock
flake.nix
home.nix

topic:chorenix-upgrade-to-nixpkg-2411-beta

chore(nix): upgrade to nixpkg 24.11 beta

---

home.nix

topic:fixzsh-disable-preinstalled-zsh-completions

fix(zsh): disable preinstalled zsh completions

---

Makefile
flake.nix
lic.nix

topic:featnix-basic-license-checking-with-nix
label:draft
relative:chorenix-upgrade-to-nixpkg-2411-beta

feat(nix): basic license checking with nix

---

Makefile
flake.nix
gcm/flake.lock
gcm/flake.nix
home.nix
nix/install.sh

topic: fixnix-update-home-manager-to-2411

fix(nix): update home-manager to 24.11

---

home.nix

topic: feat-add-macos-rectangle

feat: add macOS rectangle

---

nvim/config--nvim--init.vim.symlink

topic:fixnvim-deconflict-rebase-mapping

fix(nvim): deconflict rebase mapping

---

script/upgrade.sh

topic:fixscript-check-branch-in-dots-repo-not-current-working-directory

fix(script): check branch in DOTS repo, not current working directory

---

home.nix
nvim/config--nvim--init.vim.symlink

topic:featnvim-replace-rust-tools-with-native-inlay-hints

feat(nvim): replace rust-tools with native inlay hints

---

Makefile
flake.nix
nix/install.sh

topic:featnix-use-home-manager-through-locked-dependencies

feat(nix): use home-manager through locked dependencies

---

git/aliases.zsh

feat(git): add gcp alias

---

.gitperfconfig
flake.nix
home.nix

topic:featnix-pin-home-manager-in-home-manager

feat(nix): pin home-manager in home-manager

---

flake.lock
flake.nix
home.nix

topic: refactornix-remove-unused-nixpkg-unstable
relative:featnix-pin-home-manager-in-home-manager
labels:draft

refactor(nix): remove unused nixpkg-unstable

---

git/aliases.zsh
git/gitconfig_dotfiles.symlink

topic:featgit-fetch-tags-and-prune-always

feat(git): fetch tags and prune always

---

alacritty/config--alacritty--alacritty.toml.symlink

topic:fixalacritty-migrate-config

fix(alacritty): migrate config

---

Makefile
flake.nix
nix/README.md
nix/install.sh
nix/test.sh

topic: fixnix-add-gc-root-to-prevent-deletion-of-sources

fix(nix): add GC root to prevent deletion of sources

---

bin/nix-bindmount
bin/ssh-bootstrap

topic:featssh-bootstrap-support-bind-mount-for-nix-store

feat(ssh-bootstrap): support bind mount for nix store

---

zsh/zshrc.symlink

topic:fixzsh-add-missing-load-of-gcm-helper

fix(zsh): add missing load of gcm helper

---

git/gitconfig_dotfiles.symlink
nvim/config--nvim--init.vim.symlink

topic:fixgit-consistently-fetchall-for-git

fix(git): consistently fetchall for git

---

nvim/config--nvim--init.vim.symlink

project-specific configuration in repo files will still take precedence. Tested with pycodestyle.

feat(nvim): 120 line length by default for nvim

---

.gitperfconfig
gcm/gcm-client
tmux/tmux.conf.symlink
zsh/fix-ssh
zsh/start-gcm-helper
zsh/zshrc.symlink

topic:refactorzsh-remove-unused-gcmsocket-overrides

refactor(zsh): remove unused GCM_SOCKET overrides

---

zsh/history.zsh

topic:featzsh-manage-bigger-history

feat(zsh): manage bigger history

---

git/gitignore.symlink

topic:featgit-ignore-vscode-folder

feat(git): ignore vscode folder

---

home.nix

feat(nix): install uv

---

zsh/completion_style.zsh

Updated zsh completion styles with improved menu selection and autocomplete configurations, including custom prompts and error handling.
This addresses problems when using the dotfiles in a vscode-sized terminal with potentially too little space to show all options.
topic:autocomplete-settings

feat(zsh): enhance completion and autocomplete settings

---

nvim/config--nvim--init.vim.symlink

topic:featnvim-complete-github-pr-template-in-commit-message

feat(nvim): complete github pr template in commit message

---

tmux/tmux.conf.symlink

topic:kaihowlstack_feattmux-enable-mouse-mode

feat(tmux): enable mouse mode
