kaihowl/dotfiles

nvim/config--nvim--init.vim.symlink

To support working with conan workspaces where there is
a compile_commands.json linked into the root folder and potentially one
into the individual conan package subfolders, this change prefers the
compile_commands.json in the current working directory.
If there is no compile_commands.json in the current working directory,
the default behavior of climbing up the parent folders of the source
file for which lsp is attached is retained.

feat: prefer compilation database from current working directory

---

nvim/config--nvim--init.vim.symlink

Fixed by dropping the jremmen/vim-ripgrep plugin. The PR
jremmen/vim-ripgrep#58 is stuck and the plugin seems unmaintained since
2018. Hence, dropping the plugin and replacing it by a smaller
footprint implementation in the vimrc.

fix: calling complete without nargs for :Rg command

---

git/gitconfig.symlink

Retain old default behavior for maximum compatibility with scripts
assuming origin/master.

fix(git): suppress default branch name warning

---

nvim/config--nvim--init.vim.symlink

With a recent nvim (lsp) update the number of arguments to the callback
handler changed. Since this code's difference to the original code is
to modify the behavior in the presence of non-saved changes, we opt to
use the original handlers instead of overriding them. This saves us the
hassle of maintaining custom handlers.

fix(nvim): remove special lsp callback handlers

---

nvim/config--nvim--init.vim.symlink

Give enough history for both high and low frequency change files. Time
(6 months ago) might be a better indicator of relevance than a static
count.
A limit is needed in the first place as the performance of the quickfix
list quickly deteriorates with a large number of changes.

feat(nvim): history length of git log based on time

---

git/aliases.zsh

I found myself calling `gru!` almost always followed by `gsmu` in repos
with submodules. Hence, combining both into `gru!`. In a repo without
submodules `gsmu` is a no-op.

feat(git): update branch to upstream including submodules

---

bin/dots
homebrew/install.sh
script/bootstrap

Instead of calling `brew upgrade` with a specific list of outdated items, we leave the determination of outdated stuff up to brew itself. Sometimes on GitHub Actions runners packages like "julia" were outdated. They seemed to have switched from a formula to a cask after they were installed. Hence, providing the name forced brew to try to install "julia" as a package, which no longer existed.

fix: install / upgrade mac specifics

---

nvim/install.sh

Snap-based installs have a tendency to revert to a non-edge install.
With ppa based installs, I hope to get more stability. A non-edge based
install often breaks LSP.

feat: install nvim from ppa

---

.github/workflows/test.yml

This will become the new "lastest" for macOS on GitHub Actions.

ci: switch to macOS 11

---

nvim/config--nvim--init.vim.symlink

I don't use the plugin and it emits spurious errors in the CI run.
Fixes #39

fix: remove semantic highlight plugin

---

nvim/config--nvim--init.vim.symlink

Without nvim-lua/completion-nvim#400, any nvim version >= 0.5.1 is
incompatible with this plugin. Moreover, the repo is read-only and the
authors suggest to no longer use this plugin.

fix(nvim): remove unmaintained and broken nvim-lua/completion-nvim

---

nvim/config--nvim--init.vim.symlink

This is copied from updated documentation of help:lspconfig-keybindings.

fix: only map lsp functions if client is attached

---

nvim/config--nvim--init.vim.symlink

clangd assumes that a client with signature help is also able to deal
with bundled overload sets. This is not the case in nvim (yet).
Therefore, unpack all overload sets and show them one-by-one instead.

fix(nvim): show all overloads for clangd

---

common/pip.sh

For example ujson as part of pyls needs to be build for Hirsute. This
requires the python3 development headers.
Fixes: #70

fix: install missing python3-dev

---

nvim/config--nvim--init.vim.symlink

fix(nvim): replace deprecated nvim-cmp opts

---

system/_path.zsh

The final correction of the system path so far set the /usr/local/
paths to the front again. That means that for example a local nvim
install takes precedence over a user-installed nvim in the HOME folder.
That is unexpected. Therefore, only keeping the setting of the DOTS/bin
folder and nothing else.

fix: remove fudging of the system paths

---

nvim/install.sh
nvim/path.zsh
nvim/test.sh

Version 0.6 of nvim is released. Therefore, we no longer need to use
a nightly version. Moreover, switch to pre-compiled packages to save
time on macOS testing on GitHub Actions.
Part of #89

feat: install nvim stable with pre-compiled official package

---

nvim/config--nvim--init.vim.symlink
nvim/ripgrep.test.vim

Allow passing multiple parameters to :Rg without the user needing to
quote them. I.e., make :Rg behave the same way as `/` for searching.
Fixes: #102

fix!: escape rg integration for nvim command

---

nvim/config--nvim--init.vim.symlink

The removed autocmd group interfered with the scenario where only the
quickfix window was open. Since the definition of the autocommand group
was a little to indiscriminate, let's remove and replace it by a simple
invocation of :copen at the end of our search function.
Most importantly: This changes the behavior of an empty search. The
quickfix window will now no longer close. Instead, it will remain open
and be empty.
Part of #117

fix: fix searching with only quickfix window open

---

osx/set-defaults.sh
script/bootstrap

Allow to fail for chflags and convert all other failures into a hard
fail.
Fixes: #134

fix: macOS specific installation

---

.github/workflows/test.yml
script/install

Instead, rely on the 30 days cleanup
(HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS) and on CI hope that someone else
updates from time to time as we disable the update of homebrew for CI
explicitly. For local runs, this remains unaffected.
This has all been done in the chase of a faster CI time for macOS
builds in #122.

fix: no explicit homebrew update

---

zsh/install.sh
zsh/test.sh
zsh/userinput.test.expect

After a faulty shell linting session, each keypress led to printing out
an error. To prevent recurrence, add this test.

test: add test for zsh user input

---

nvim/path.zsh

After migrating to a user-installed nvim, the snap path is no longer
necessary.

fix: remove outdated snap path for nvim

---

homebrew/relink.zsh

The LinkedKegs folder is not even available anymore.

chore: remove unused relink script instead of fixing it

---

zsh/userinput.test.expect

Instead of using ctrl-c to clear up previous erroneous input (only
appears on Github Actions Ubuntu runner), use ctrl-w. This was
necessary as the test failed local execution.

test: make userinput zsh test more stable

---

nvim/completion.test.vim
nvim/config--nvim--init.vim.symlink

Such that reaching the end/start of a document with no further matches
becomes conspicuous.
Fixes #105

feat: do not wrap on search

---

zsh/test.sh

The signal-to-noise ratio is too low right now. Therefore, raising the
expectation to still catch vast outliers but to also not be broken for
singular start up problems on a CI with noisy neighbours.
Part of #170

perf: increase zsh startup expectation to 300 ms

---

zsh/zshrc.symlink

perf(zsh): reuse cached BREW_PREFIX across zsh startups

---

.github/workflows/test.yml

We want concurrent pull requests to be allowed. For this, we need the
CI to run on the master branch as well.

ci: always run ci

---

nvim/config--nvim--init.vim.symlink

* Only attempt to create undo directory if is does not yet exist.
* Don't shell out but use built-in functions
* Optimize (about 20 out of 30 ms) edge load time by deferring
Fixes #194

perf(nvim): optimize start up time

---

nvim/config--nvim--init.vim.symlink

nvim is always `nocompatible`.

fix(nvim): remove nocompatible from nvim config

---

nvim/config--nvim--init.vim.symlink

Single quote strings are taken literal and do not expand escape
sequences etc.

fix(nvim): single-quote strings

---

nvim/config--nvim--init.vim.symlink

Use comparison operators that are independent of the user's
`ignorecase` setting.

fix(nvim): use stable comparison operators

---

fzf/aliases.zsh

feat(fzf): split tmux capture-pane input on whitespace, use ctrl-xo

---

common/apt.sh
common/brew.sh
zoxide/install.sh

Without the explicit removal, there might still be compdef definitions
that conflict with zoxide's 'j'.
Fixes #207

fix: remove autojump explicitly

---

fzf/aliases.zsh

When sifting through a list of sorted input, e.g., git-log, do not
resort and only apply filtering.
Fixes #218

fix: for sorted fzf git aliases, keep the sort order

---

clangd/install.sh

When on CI, the stdout is indeed not a terminal. As we are not parsing
the output, the warning is too unspecific. Setting to a non-empty value
when running on CI will remove the warning.

chore: remove spurious apt-key warning

---

osx/set-defaults.sh

When using the keyboard preferences in OSX, the value "2" is the
fastest setting. Setting it to "0" will increase it too a much too high
value. This is obstructing using j/k keys for scrolling line by line in
a sensible way.

fix(osx): set default key repeat to fastest value available in UI

---

nvim/config--nvim--init.vim.symlink
nvim/test.sh

This was broken in earlier commits to enable submodule support.
Fixes #236

fix(nvim): detect remote default git branch

---

nvim/config--nvim--init.vim.symlink

With streaming input into the preview window, a hanging git-fetch is
indistinguishable from a finished but empty git-fetch.
Hack around this by making git-fetch verbose.

feat(nvim): verbose fetch

---

nvim/test.sh

Instead of indiscriminately parsing all headless output (including
potential, irrelevant error messages), only parse stdout. For that
headless mode has to explicitly enable stdout and send the desired
output to stdout.

test(nvim): stabilize git folder tests

---

nvim/config--nvim--init.vim.symlink

This fixes one of the problems in #247.

feat(nvim): use 'jj' mapping to escape terminal mode

---

nvim/config--nvim--init.vim.symlink

Right screen single letter in status line for [s]uccess, [f]ailure, and
[r]unning.
Fixes #253

feat: minimal asynctasks status indicator

---

nvim/config--nvim--init.vim.symlink

We don't want the command to be output when invoking the window.

fix(nvim): silent fzf mappings

---

bin/git-zlog

This allows to use git-zlog to show differences for commit range
updates when fetching.
Fixes #267

fix: allow git-zlog to ignore releases when 'since' is specified

---

nvim/config--nvim--init.vim.symlink

feat(nvim): keep right for long file names when switching buffers

---

TODO
nvim/config--nvim--init.vim.symlink

First, this frees me from maintaining my own fzf sources for :buffers.
Second, this introduces live_grep and fixes https://github.com/kaihowl/dotfiles/issues/269.
Third, this introduces new bindings for fzf on :changes and :jumps.

fix(nvim): use fzf-lua

---

nvim/config--nvim--init.vim.symlink

This temporarily pins the in-review PR. Once that is merged, we revert
back to using upstream.
Fixes: #268

fix(nvim): no concurrent interleaving quickfix output with asyncrun

---

nvim/config--nvim--init.vim.symlink

The previous gymnastics of calling `filetype off` and `filetype indent
plugin on` were only needed in Pathogen. I seem to have copied this
over when starting a fresh vimrc by using stevelosh's defaults.
With using Plug as the plugin manager instead, the filetype and syntax
enabling is handled already.
Removing the superfluous commands removes sourcing of ftoff and an
additional sourcing of filetype.vim. This saves about 10 ms of start up
time overall.

fix(nvim): only source filetype.vim once

---

nvim/config--nvim--init.vim.symlink

Do not follow symlinks (that are potentially broken). Reuse the
original arguments used for rg before fzf / fzf-lua replaced ctrlp.

fix(nvim): fix sporadic output errors in fzf-lua files

---

TODO
nvim/config--nvim--init.vim.symlink

Moreover, remove outdated TODO file.

fix(nvim): do not error on missing fzf-lua module when installing

---

nvim/config--nvim--init.vim.symlink

To just browse through the history of a single file, the range given to
the Gclog command should not contain the entire file. This
unnecessarily slows down both the git command as well as the quickfix
parsing of the output: The entire file for each revision is parsed.
Instead, pass a zero context to the Gclog command.
This was erroneously introduced in 7c668d8.
Fixes #283.

perf(nvim): do not use range context for git-log per default

---

nvim/config--nvim--init.vim.symlink

Allows to quickly jump through the git history of a file by limiting to
a specific set of lines.
This is a follow up to #283.

feat(nvim): add visual git log

---

nvim/config--nvim--init.vim.symlink

For a simple git-log, restoring of the cursor will work for a single
file and single revision. As soon as I jump to the next file in the
quickfix list, the cursor position is gone.
If I want to restrict the git log to a specific set of lines, there is
a visual git log mapping that is superior. I will use that.
This commit removes the unnecessary wrapping of the git log Gclog
invocation in the RestoreCurPos.

fix(nvim): do not restore cursor position for git-log

---

nvim/install.sh

Otherwise, on a non-fresh system the clean / upgrade might fail since
the prompts asking for confirmation do not work in headless mode.

fix(nvim): ensure unattended vim-plug update and clean

---

nvim/config--nvim--init.vim.symlink

fix(nvim): if qf is empty for PR, do not attempt to open

---

tmux/statusline.conf

This increases compatibility with vim color schemes edge/gruvbox which
use the same color for PmenuSel highlights. The bright blue is easier
on the contrast.

feat(tmux): use brightblue for statusline

---

tmux/statusline.conf

I don't really need thick borders for tmux. Hence, remove the option
that is only available in newer tmux versions.
Fixes #310

fix(tmux): remove invalid, too new option

---

zsh/zshrc.symlink

Without it, user-defined completions will not be present.

fix(zsh): add missing compinit

---

zsh/zshrc.symlink

Partially helps with #170 
Current master as a 60 ms regression. This fixes about 30 ms of that regression. Without breaking the possibility of adding custom completions in my dotfiles, I cannot simply revert to the original. Currently though, there are no custom completions taking advantage of this.

perf(zsh): do not call compinit twice

---

zsh/fpath.zsh

Scanning directories that do not contain additional functions decreases
performance unnecessarily.
Fixes #170

perf(zsh): selectively add fpath instead of globally

---

fzf/test.sh
zoxide/completion.zsh
zoxide/path.zsh
zoxide/test.sh
zsh/test.sh
zsh/zshrc.symlink

First set up fpaths, then call omz to do compinit, then load
customizations on top.
Setting up fpath after omz would require a second compinit call that
leads to constant rewriting of the cache.
Setting up omz last (as was done before this patch) leads to
overwriting our keybindings as `bindkey -v` is called during omz setup.
This will reset all keybindings and initialize the vi-keybindings.
Fixes #324

fix(zsh): fpath initialization order

---

nvim/config--nvim--init.vim.symlink

This works more consistently across a range of color schemes.

fix(nvim): clean up coloring of statusline

---

nvim/config--nvim--init.vim.symlink

With current colorschemes this is more of a distraction than helpful.
It gets hard to distinguish the end of a window with the end of a line.
Fixes #337

feat(nvim): remove cursorline

---

.github/workflows/test.yml
zsh/test.sh

- Increase zsh performance expectation to account for recent slow down
(#346).
- Unlink git on macOS such that brew install can succeed (#347).

ci: breakfix CI issues

---

nvim/config--nvim--init.vim.symlink

This guarantees wider compatibility across color schemes.
Fix #370

fix(nvim): use built-in highlight groups for asyncrun_status

---

nvim/config--nvim--init.vim.symlink

'Substitute' is not consistently "yellowish" for signalling a running
task. Try instead with 'DiffText' for a running task, 'DiffDelete'
for a failed task, and 'DiffAdd' for a successful task.

fix(nvim): apply consistent colors for asynctask across colorschemes

---

script/check_for_upgrade.sh

The dots file was updated twice (harmless) when an actual upgrade of
the dotfiles took place.

fix(script): remove double update of dots file

---

homebrew/install.sh
script/.gitignore
script/check_for_upgrade.sh
script/upgrade.sh
zsh/install.sh

Prevent concurrent invocations when multiple shells are opened.
Expected flow:
- I open a new shell for the first time on a day.
- Updates to dotfiles are detected.
- I switch to a second new shell.
-- pending update is detected.
-- but I can start working on this shell.
-- first shell continues updating.
- Dotfiles are updated from git.
- Bootstrap is run.
- Install is run.
This change also includes asking for the my sudo upfront and
changes the invocation for chsh to use sudo as well. This way I am
asked only once for the password in case there are changes and an
upgrade has to run.

feat!(script): automatically run bootstrap/upgrade for new changes

---

fzf/install.sh

Instead of installing zsh for the fzf install, only check if zsh is
available. If not, fail.
This is still a suboptimal solution but it will
- prevent installing zsh and omz twice
- fail loud and clear in case that the script/install order changed and
fzf is installed before zsh.
Better solution is to define the dependency tree between install
scripts and sort them topologically.

fix(fzf): no double install of zsh

---

colors/change-color

fix(nvim): restore colorscheme edge specific options

---

gdb/install.sh

There is no proper virtual package to install the correctly versioned
package for the debug symbols.
I also could not find a way to detect the currently installed version
easily to use that information to choose the right version of the
package for the debug symbols.
Since we have a test, this will fail if we for example update to
a later Ubuntu version.

chore(gdb): Remove non-actionable todo

---

script/upgrade.sh

Even if there is no update to the dotfiles themselves, there might be
dependencies that have updates. We want to ingest them as quickly as
possible. Therefore, unconditionally update.

fix(script): always bootstrap and install

---

script/ci.sh

We initially accepted 6 sigma deviations as there were too few
measurements to have a more strict (and default) 4 sigma acceptance.
This is a flaw in git-perf and must be fixed there. I.e., if there are
not a minimum number of measurements, accept any measurement.
This change reverts 64307f8 and reintroduced the default 4 sigma
acceptance.

fix(ci): only accept 4 sigma deviations

---

nvim/lsp-completion.test.vim
nvim/test.sh

Remove indirection with second function and immediately input and use
omni-complete function.
Also remove unnecessary `redraw` call.
Fixes #427

test(nvim): fix test for nvim-cmp

---

gdb/gdbinit.symlink
gdb/install.sh
gdb/test.sh

fix(gdb): install correct version of debug symbols for Ubuntu 22.04

---

pyls/install.sh

This is included as an optional dependency in python-lsp-server when
specifying `all`. An explicit install of the latest autopep8 can
conflict with the version specified by python-lsp-server.

fix(pyls): no need to install autopep8 explicitly

---

script/ci.sh

This ensures that newly added measurements only start to count for
audit once there are enough measurements to ascertain the stddev.

ci: require a minimum of 10 measurements

---

nvim/config--nvim--init.vim.symlink

This converts to using one-file-per-line view with change stats for the
PR overview of a branch compared to the merge base. The additional
benefit of this view is that moved-but-not-changed files appear as
well.
Fixes #432

feat(nvim): use stat-style view for PRs

---

zoxide/install.sh

The manual restructuring of man pages is no longer necessary. Workaround removed.

chore(zoxide): update to 0.8.3

---

nvim/config--nvim--init.vim.symlink

After nvim 0.8.0, indent guides and trailing whitespace was highlighted on the terminal window. Exclude the fzf filetype for both plugins.
Hotfix for #470
Unclear what changed in nvim 0.8.0 to start triggering these plugins. Not worth to investigate further, though: There was no use case for both plugins on the fzf terminal window anyhow.

fix(nvim): do not show trailing whitespace / indent guides on fzf

---

nvim/config--nvim--init.vim.symlink

fix(nvim): replace deprecated formatting_sync

---

nvim/config--nvim--init.vim.symlink

fix(nvim): replace deprecated cmp-nvim-lsp function

---

nvim/test.sh

Upstream has disabled file as a transport mode for cve-2022-39253.
Fixes #488

fix(nvim): test for submodule breaks with git 2.38.1

---

system/install.sh

This is for example assumed to be present on the host system for conan packages to compile. Let's install them by default.
Fixes #467

feat(system): install automake, libtool, pkg-config

---

nvim/tests/asyncrun-errorformat.test.vim

We might not receive less but also more items. Therefore, remove 'only' in the error output.

test: clarify error output

---

clangd/install.sh
clangd/path.zsh
clangd/test.sh

Support for llvm on homebrew for Catalina seems broken. Since llvm is a too heavy-weight dependency anyhow (for just using clangd of it), switch to a GitHub releases installation flow.
Fixes #505

fix(clangd): install clangd from github releases

---

nvim/tests/asyncrun-errorformat.test.vim
script/ci.sh
zsh/install.sh

This submits three small fixes found during running in a bash "strict"
mode for all spawned shells. Due to advice from
https://wiki.bash-hackers.org/scripting/obsolete, I am not sure if
there is much value in setting errexit, etc. on install scripts. It is
already set in test scripts, where I believe it is crucial.
- make asyncrun-errorformat.test.vim less sensitive
- an empty array (stdbuf in ci.sh) is considered an unbound variable
- fix an unbound variable in zsh/install.sh
Fixes https://github.com/kaihowl/dotfiles/issues/493

fix: improve shell handling / tests

---

script/bootstrap
script/check_for_upgrade.sh
zsh/window.zsh

Shellcheck 0.9.0 finds one unquoted comparison and multiple false positives in control flow analysis.
Fixes #510

fix: shellcheck findings

---

nvim/config--nvim--init.vim.symlink
nvim/test.sh
nvim/tests/asynctasks.test.vim
nvim/tests/test-asynctasks/.tasks
nvim/tests/test-asynctasks/test/.tasks

Always drive the execution of tasks from the .tasks file of the current working directory. For a submodule context where both the main git working copy and the submodule, this allows choosing the project scope based on the current working directory.
Part of #517

feat(nvim): simplify asynctasks for submodules

---

nvim/config--nvim--init.vim.symlink

Align fzf-lua git branch behavior with fugitive: When a file from a submodule is the current file, use this files git dir instead of the git dir detected from the cwd.
Finishes #517

feat(nvim): fzf-lua git branch allow switching submodule branches

---

nvim/config--nvim--init.vim.symlink

fix(nvim): freeze vim-trailing-whitespace at last working commit

---

common/utilities.sh
fzf/install.sh
system/install.sh
system/test.sh

- only install ncdu/wget on macOS 11 and later
- zig as a dependency of ncdu is no longer available pre-Big Sur
- only install wget/curl if not yet there

fix(system): restore clean install run on Catalina

---

nvim/tests/editorconfig.test.vim
rust/install.sh
rust/test.sh

Use the official install script instead to install rust. Directly using the rustup-init binaries means I will have to maintain the detection logic for OSs, cpu architectures, and clibs.

fix(rust): use correct clib type

---

nvim/config--nvim--init.vim.symlink
nvim/tests/editorconfig.test.vim

Also revert "test(nvim): disable failing test (#539)"
This reverts commit dc39447fb24897595246541e5707410b3e618d6d.
Part of #538

fix(nvim): pin last working version of editorconfig

---

nvim/config--nvim--init.vim.symlink

The upstream fault from #531 is fixed.
Fixes #531.

fix(nvim): switch back to upstream vim-trailing-whitespace plugin

---

nvim/config--nvim--init.vim.symlink

No workaround for #538 needed anymore as upstream was fixed.
Fixes #538

chore(nvim): update to upstream editorconfig

---

nvim/config--nvim--init.vim.symlink

Fixes #546 with a work around.
By explicitly calling `redraw`, we make neovim/neovim#14565 dormant. The failure is triggered by requiring a redraw before the completion menu can be made visible. At least this is my understanding.
Work around the issue by forcing the redraw ourselves as part of the conventional commit completion code, which enables the original fault.

fix(nvim): make nvim segfault dormant again

---

zsh/zshrc.symlink

Allow running with non-standard checkout path. Therefore, infer the location of the dotfile checkout by canonicalizing the symlinked file.
Part of #550

feat(zsh): infer dots location from symlink

---

.github/workflows/test.yml
script/bootstrap

In codespaces, this information is already set and should be used (and duplicated into the git credentials file. Without duplicating, we run the risk that the original source of the preset values is altered. This is a change in behavior.
This change allows dotfiles to be used in the setup of a codespace.
Part of #550.

feat(script): user preset git user values when available

---

script/bootstrap

To allow for automatic bootstrapping in GH codespaces and CI, decide to backup existing files. This makes the script suitable for automatic use.
Part of #550.

feat(script): always backup symlinked files in codespaces/CI.

---

script/bootstrap

codespaces expose the values in the system context, not in the global context. To allow for both system and global context, do not narrow the context. This also allows for local contexts to be elevated to global context unfortunately. As there is no strong reason to prevent this right now, let's keep it simple.
Part of #550.

fix(script): detect user/email for git from non-global context

---

README.md
script/bootstrap
script/ci.sh
script/upgrade.sh

To allow one-command install and therefore support in the Codespaces setup for dotfiles, we need to immediately call install after the setup step.
Part of #550

refactor: trigger install from bootstrap step

---

nvim/test.sh

Without pipefail, the error from the first grep command checking for "error" in the health file is not propagated.
More critically, the healthcheck file is never written as vim refuses to overwrite the created but empty temporary file.
Fixes #571

test(nvim): fix healthcheck tests

---

nvim/config--nvim--init.vim.symlink

This is a fixup to 87825a3 which unfortunately wiped out indexing any other buffer than the current buffer. The current buffer was correctly skipped if too big.
This change restores indexing of other buffers (but still checks the maximum size).
Fixes #574

fix(nvim): skip _only_ big buffers for completion

---

nvim/tests/t_comment.test.vim

With nvim 0.9, the default commentstring is empty and this test will fail instead.

test(nvim): do not rely on default commentstring

---

nvim/install.sh

Left-behind files from previous versions can leave to strange behavior. This is also flagged by the :healthcheck command.
Fixes #583

fix(nvim): ensure clean install

---

TODO
nvim/config--nvim--init.vim.symlink
nvim/install.sh

Update to nvim 0.9.
Remove deprecated paste toggle and superfluous editorconfig plugin.
Enable newly added linematch second-stage diff.

chore(nvim): upgrade to nvim 0.9.0

---

alacritty/install.sh

Only launchpadcontent offers https. Launchpad.net is maintained for compatibility reasons only.
Fixes #594

fix: use launchpadcontent instead of launchpad

---

alacritty/install.sh

Installing an already installed cask now became a hard error. Work around this until an upstream solution is found.
Part of #605

fix(alacritty): workaround for already installed cask

---

nvim/config--nvim--init.vim.symlink

Moreover, switch to a modern plugin with better future support.
Fixes #600

feat(nvim): exclude terminals on indent guides

---

bin/waiting-apt-get
common/apt.sh
script/install

To ensure that after startup we can run successfully through script/install even if packagekitd temporarily holds the apt lists lock, we wait once for this lock.
Fixes #618

feat(script): wait for apt lists lock once

---

git/gitconfig.symlink

In repos without this file, git-blame will error out.

fix(git): do not apply a global ignoreRevsFile

---

alacritty/config--alacritty--alacritty.yml.symlink

Necessary to use alt-a in fzf to select all matches.

fix(alacritty): use both option keys on macOS as meta keys

---

nvim/tests/fzf-git.test.vim

The test should have failed when encountering errors. First, fix the test and restore functionality. Second, ensure that any failures in lua, lead to a failure of the test.
Part of #644

fix(nvim): call correct function in test

---

nvim/config--nvim--init.vim.symlink
nvim/tests/fzf-git.test.vim

Fixes #643
Introduces a prompt showing "lua-fzf.Files"-like shortened path. Paths in the results as well as in the commands are always relative to the current git worktree.

fix(nvim): fzf git preview for different git dir than pwd

---

nvim/config--nvim--init.vim.symlink
nvim/tests/fzf-git.test.vim

fix(nvim): fzf git log on fugitive special commit

---

osx/install.sh

Install rosetta on macOS unconditionally. Assume that no Intel mac is used anymore.
This is needed to run shellcheck for example.
Fixes #660

feat(osx): automatically install rosetta

---

nvim/config--nvim--init.vim.symlink

"p" must come first to make it an absolute path.

fix(nvim): absolute file path for fzf git branch switch

---

zsh/pattern-search.zsh

Since the introduction of fzf, these key bindings are no longer relevant.

fix(zsh): delete superfluous key bindings

---

script/bootstrap

Neither -f nor -e (or any other file check) recognizes a broken symlink as "existing", i.e., "the file name is occupied".
Fixes #674

fix(script): allow overwriting of broken symlink

---

osx/set-defaults.sh

feat(osx): start GnuCash always in German

---

nvim/config--nvim--init.vim.symlink
nvim/tests/fzf-git.test.vim

fix(nvim): fzf vertical split for git

---

.github/workflows/test.yml
nvim/test.sh

macos-11 no longer has pre-built packages (and support) from Homebrew.

ci: use macos-12

---

system/install.sh
system/test.sh

I am not using it. It builds dependencies from scratch in homebrew. Let's save some time.
Edit: the reason for building was the deprecation of mac-11. With #707, macos-11 was replaced by macos-12. This no longer makes this change strictly necessary.

fix(system): remove lnav

---

bin/termtest
nvim/nvim-alias.zsh
tmux/install.sh
tmux/tmux-256color.terminfo

With macOS sonoma, ncurses is updated to 6.0. This includes a tmux-256color config and our custom config is no longer needed.
Fixes: #700

fix(tmux): no manual terminfo for Sonoma

---

common/python.sh
nvim/config--nvim--init.vim.symlink
nvim/install.sh

Since the provider is unused, we don't need to fix the python3.12 incompatibility. Moreover, disable all external providers that are checked in the healthcheck.
Fixes: #703
Revert "fix(python): force python 3.11 (on macOS) (#704)"
This reverts commit 1f5118deeb52441ca9fd6feb8da7b3fe6784b465.

fix(nvim): drop unused pynvim provider

---

nvim/test.sh

Not only check the health file for errors but also the process host file for errors.
Remove filtering for node provider error. This has instead been disabled in the configuration with 746d5d2 now.
Fixes: #710

fix(nvim): check for all install errors

---

clangd/install.sh

The release is still marked as pre-release. Upstream 17.0.3 has been released. I don't see a reason to not assume that this has been done in error. Let's start using 17.0.3 despite the "pre-release" state.

chore(clangd): update clangd to 17.0.3

---

zsh/p10k.zsh.symlink

Instead of magenta / red, which is almost indistinguishable.
Fixes #717

fix(zsh): grey (normal) / red (failed) prompt

---

cmake/install.sh
common/apt.sh

As the signing key for the kitware repo is not published on the ubuntu
keyserver anymore, we reinstate the automatic key rotation support.
This breaks consistency with other packages.
The apt.sh function are restructured accordingly.
Fixes: #726

chore(cmake): update keyid

---

.github/workflows/test.yml

Motivated by fixing a deprecation warning about an outdated node
runtime.

ci: bump checkout action

---

nvim/config--nvim--init.vim.symlink

fix(nvim): do not rely on cached resume data for fzf-lua

---

nvim/config--nvim--init.vim.symlink

Keep the order as present in git.
Fixes #749

feat(nvim): do not sort fzf git log entries

---

common/python.sh

Somehow when install_in_virtualenv is called twice from the pyls install script, SCRIPT_DIR is no longer set to the right value inside the common/python.sh script.
To prevent this, make SCRIPT_DIR a local variable script_dir instead.

fix(common): prevent accidental overwrite of SCRIPT_DIR

---

pyls/install.sh

Enable black as the default formatter. This plugin does not allow configuring a different formatter on a project by project basis. As black is a wildly used formatter, this is acceptable to me.

feat: support python black as a formatter

---

nvim/tests/fzf-git.test.vim

With https://github.com/ibhagwan/fzf-lua/commit/f1c65edce7889181b083f85a98db2e0f69cab926, the prompt change to no longer contain the `>` character as a prefix.

fix(nvim): fix test with changed inline prompt

---

nvim/config--nvim--init.vim.symlink

removal needed as the healthcheck checks for lldb-vscode install, which we currently don't have.

fix(nimv): remove unused dap plugin

---

nvim/tests/lsp-completion-rust.test.vim

Due to #779
Topic: disable-test

test(nvim): disable lsp-completion-rust.test.vim

---

.github/workflows/test.yml

This fixes a breaking change to the upstream tag version.

fix(ci): include hidden files by default

---

git/gitconfig.symlink

Many github templates use # to start an h1. title. This conflicts with
the git comment marker. Deconflict by using a semicolon instead.
topic:git-comment-marker

feat(git): set semicolon as comment char

---

revup/path.zsh

Do not modify the PATH to also contain the python3 of the revup
virtualenv.
topic:revup-fix
relative:bash-test

fix(revup): only export revup binary

---

alacritty/test.sh
ccache/test.sh
clangd/test.sh
cmake/test.sh
colors/test.sh
ctags/test.sh
efm/test.sh
fzf/test.sh
git/test.sh
ninja/test.sh
nvim/test.sh
revup/test.sh
ripgrep/test.sh
rust/test.sh
shellcheck/test.sh
system/test.sh
vint/test.sh
virtualenvwrapper/test.sh
zsh/test.sh

With nix-installed (or other non-distro packet managers) zsh won't be
installed at the default `/bin/zsh` path. Prepare for this change by
using `/usr/bin/env zsh` to discover zsh from the PATH instead.
topic:zsh-path-test

refactor: zsh shebang based on env

---

alacritty/test.sh
bin/git-zlog
ccache/test.sh
clangd/test.sh
cmake/test.sh
colors/test.sh
ctags/test.sh
efm/test.sh
fzf/test.sh
git/test.sh
ninja/test.sh
nvim/test.sh
revup/test.sh
ripgrep/test.sh
rust/test.sh
shellcheck/test.sh
system/test.sh
vint/test.sh
virtualenvwrapper/test.sh
zsh/test.sh

The invocation for interactive/login shell is no longer exclusively
driven by the script/test program.
topic: test-standalone

fix: test scripts can run standalone again

---

bin/dot-export
bin/termtest
colors/bin/change-color
script/check_for_upgrade.sh
script/upgrade.sh
zsh/zmv.zsh

With nix-controlled packages, zsh will no longer be present on
/bin/zsh. Account for that in scripts.
topic: zsh-env

fix(bin): use env-based zsh

---

.gitperfconfig

macos latest got faster in CI measurement. Not investigated further.
topic: faster-ci

ci: accept faster CI time

---

zsh/install.sh

As prep for using a nix-installed zsh, do not directly change the shell
for the user. In case that the nix-installed shell is not available or
fails to start, we risk a complete lock out.
With a safe-exec of the zsh binary in the profile, we can fallback to
the default login shell of the user.
topic: safe-zsh
relative-topic: faster-ci

feat(zsh): load zsh with exec in profile instead of chsh

---

script/install

Correctly order the install of nix, the sourcing of the nix daemon env,
and the attempt to install the home-manager and its env.
With the previous interactive shell, calling upgrade.sh in an already
interactive shell leads to not executing the install and having
a nested shell.
topic: shell-nix

fix(nix): no-interactive shell needed for install

---

git/gitconfig.symlink
git/gitconfig_credentials.example
script/bootstrap

This also allows to handle forward ssh keys that are not local to the
current machine.
topic:remote-git-ssh

feat(git): configure signing key from key agent

---

nvim/config--nvim--init.vim.symlink

This now leads to errors when displaying the config--nvim--init.vim
file. The heredocs with lua looks sufficiently correct in syntax
highlighting to not warrant the workaround.
topic: remove-treesitter-workaround

fix(nvim): remove workaround for treesitter

---

.github/workflows/test.yml
common/perf.sh
common/perf_stubs.sh
nvim/config--nvim--init.vim.symlink
script/ci.sh
script/install
script/test

Make lsp config conditional for non-installed LSP servers. Otherwise,
the healthcheck of nvim fails.
Keep the old performance measurements. For the minimal profile, append
"-minimal" to the current os label. We do not support multiple labels
in the audit processing as of today.
topic: minimal-ci

fix: add ci for minimal profile

---

script/install

Not even homebrew seems to need that anymore. Let's remove the hard
requirement.
topic:no-xcode

fix(macos): remove unnecessary full xcode install

---

git/gitconfig_credentials.example
git/gitconfig_dotfiles.symlink
git/install.sh
script/bootstrap
script/install

This does not migrate existing installations.
We want existing global git configs to continue to exist. We add our
additions to the git config at the bottom through an include instead.
topic: git-config-global

feat(git): allow existing git config to coexist

---

colors/bin/change-color
home.nix
nvim/config--nvim--init.vim.symlink

Make gruvbox the new default as edge modifies the non-writable plugin path on lazy load.
See https://github.com/sainnhe/edge/issues/79.

chore(nvim): move available color schemes to nix

---

home.nix
nvim/config--nvim--init.vim.symlink

topic: chorenvim-move-completion-plugins-to-nix
relative:chorenvim-move-available-color-schemes-to-nix
labels:draft

chore(nvim): move completion plugins to nix

---

home.nix
nvim/config--nvim--init.vim.symlink

topic: chorenvim-remove-unused-fugitive-handler--move-rhubarb-to-nix
relative: chorenvim-move-completion-plugins-to-nix
labels: draft

chore(nvim): remove unused fugitive handler / move rhubarb to nix

---

home.nix
nvim/config--nvim--init.vim.symlink

topic: chorenvim-move-asyncrunasynctasks-to-nix
relative: chorenvim-remove-unused-fugitive-handler--move-rhubarb-to-nix
labels:draft

chore(nvim): move asyncrun/asynctasks to nix

---

home.nix
nvim/config--nvim--init.vim.symlink

topic:chorenvim-move-last-two-easily-available-plugins-to-nix
relative: chorenvim-move-asyncrunasynctasks-to-nix
labels:draft

chore(nvim): move last two easily available plugins to nix

---

colors/bin/change-color

Based on
https://github.com/sainnhe/edge/issues/79#issuecomment-2543904156,
disabling the edge_better_performance setting such that no files are
generated in the plugin folder. This would other break nix which has by
design an immutable store.
topic:fixcolors-fix-edge-color-scheme-and-nix-behavior

fix(colors): fix edge color scheme and nix behavior

---

home.nix
nvim/config--nvim--init.vim.symlink

topic:chorenvim-last-plugin-vim-textobj-argument-moved-to-nix
relative:chorenvim-move-vim-indent-sentence-to-nix
labels:draft

chore(nvim): last plugin, vim-textobj-argument moved to nix

---

home.nix

On macOS, the `--apple-use-keychain` option is otherwise unknown.
topic:fixnix-only-install-custom-openssh-on-linux-systems

fix(nix): only install custom openssh on linux systems

---

zsh/test.sh
zsh/userinput.test.expect
zsh/zshrc.symlink

Only runs on macOS. Did not spend more time on figuring out the
flakyness on Ubuntu.
Includes a couple robustness improvements.
topic:fixzsh-reenable-zsh-test

fix(zsh): reenable zsh test

---

zsh/autosuggestions.zsh

The performance hit the rebinding widgets imposes, is not observable by
me. I have _not_ benchmarked this, yet I did not notice any difference
in day-to-day usage. Also with zprof, I could not spot the function in
which this parameter is used.
Removed to clean up config.
topic:fixzsh-remove-unnecessary-zshautosuggestmanualrebind

fix(zsh): remove unnecessary ZSH_AUTOSUGGEST_MANUAL_REBIND

---

bin/safe-reattach-to-user-namespace
home.nix

This functionality is incorporated into tmux since version 2.6
according to https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard.
Remove the workarounds.
topic:chore-remove-reattach-to-user-namespace

chore: remove reattach-to-user-namespace

---

Makefile
flake.nix
script/test

Only run this as part of CI once.
topic: refactornix-move-license-check-into-separate-attribute

refactor(nix): move license check into separate attribute

---

bin/ssh-bootstrap

topic:fixssh-bootstrap-git-status-check-when-pwd--dots

fix(ssh-bootstrap): git status check when pwd != dots

---

zsh/install.sh
zsh/start-zsh

topic:fixzsh-only-enter-zsh-from-bash-when-interactive

fix(zsh): only enter zsh from bash when interactive

---

script/test
zsh/zshrc.symlink

For #939, we cannot use a login shell as the nix daemon script putting the profile bin directory in front of everything else in the PATH will already have run once and exported the env var to prevent duplicated running. Running as a login shell for tests will only run the macOS specific helpers to put system binaries in front of the PATH again. This ultimately will mean that for a nested login shell, the system path libraries will precede the nix installed ones.

fix: no login shell for tests

---

git/gitconfig_dotfiles.symlink

When working from multiple workspaces, prevent overwriting your own changes.

feat(git): pub alias with force-with-lease

---

virtualenvwrapper/test.sh

The function for `workon` contains `error:` which we pick up as an
error in the CI output.
topic:fixzsh-which-test-should-not-print-full-function-definition

fix(zsh): `which` test should not print full function definition

---

bin/ssh-tag
ssh/ssh--config_dotfiles.symlink

Only for explicitly tagged hosts, forward credentials of any kind.

feat(ssh): only target tagged machines

---

nvim/config--nvim--init.vim.symlink

Accept behavior change for Rhubarb to not be called for findstart
anymore.
topic:refactornvim-move-common-code-to-top-for-omnifunc-function

refactor(nvim): move common code to top for omnifunc function

---

.github/workflows/test.yml
script/versions.sh

The reporting of vim plugins was broken since the switch to nix. With
statically determined versions, there is no need to report versions in
the first place.
topic:kaihowlstack-fix-disable-version-reporting

fix: disable version reporting

---

nvim/config--nvim--init.vim.symlink

topic:kaihowlstack_featnvim-use-a-different-separator-for-the-branch-topic-name

feat(nvim): use a different separator for the branch topic name
